<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

use App\Http\ApiV1\Modules\Comments\Controllers\CommentsController;
use Illuminate\Support\Facades\Route;

Route::get('comments', [CommentsController::class, 'getByStepId'])->name('getByStepId');
Route::post('comments', [CommentsController::class, 'create']);
Route::delete('comments', [CommentsController::class, 'delete']);
Route::patch('comments', [CommentsController::class, 'update']);
