openapi: 3.0.3
info:
  title: Comments Service
  version: 1.0.0
  license:
    name: AGPLv3
  description: Comments Service REST API
  contact: 
    name: your mom

servers:
  - url: /api/v1
tags:
  - name: comments

paths:
  /comments:
    $ref: './comments/paths.yaml#/Comments'

components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
    QueryId:
      $ref: './common_parameters.yaml#/QueryId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
          - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
